Repository nicholasgrose/Gateway, pull requests merged in 2022-12, with the labels that each got.

#45 Made whitelist removal work again
  src/main/kotlin/com/rose/gateway/minecraft/whitelist/Whitelist.kt
Labels: bug

#46 Fixed join messages
  src/main/kotlin/com/rose/gateway/minecraft/chat/ConnectionListener.kt
Labels: bug

#50 Beautified Discord slash commands
  gradle.properties
  src/main/kotlin/com/rose/gateway/config/access/AboutExtensionEnabled.kt
  src/main/kotlin/com/rose/gateway/config/access/BotConfiguration.kt
  src/main/kotlin/com/rose/gateway/config/access/ChatExtensionEnabled.kt
  src/main/kotlin/com/rose/gateway/config/access/IpExtension.kt
  src/main/kotlin/com/rose/gateway/config/access/ListExtension.kt
  src/main/kotlin/com/rose/gateway/config/access/MinecraftConfig.kt
  src/main/kotlin/com/rose/gateway/config/access/TpsExtensionEnabled.kt
  src/main/kotlin/com/rose/gateway/config/access/WhitelistExtension.kt
  src/main/kotlin/com/rose/gateway/config/extensions/BotConfiguration.kt
  src/main/kotlin/com/rose/gateway/config/schema/ListConfig.kt
  src/main/kotlin/com/rose/gateway/config/schema/MinecraftConfig.kt
  src/main/kotlin/com/rose/gateway/config/schema/WhitelistConfig.kt
  src/main/kotlin/com/rose/gateway/discord/bot/BotContext.kt
  src/main/kotlin/com/rose/gateway/discord/bot/DiscordBot.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/about/AboutExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/chat/ChatExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/chat/processing/DiscordMessageProcessor.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/chat/processing/UserMentionTokenProcessor.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/ip/IpExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/list/ListExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/tps/TpsExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/whitelist/WhitelistExtension.kt
  src/main/kotlin/com/rose/gateway/discord/bot/message/GroupAndPaginateItems.kt
  src/main/kotlin/com/rose/gateway/discord/bot/presence/BotPresence.kt
  src/main/kotlin/com/rose/gateway/minecraft/CommandRegistry.kt
  src/main/kotlin/com/rose/gateway/minecraft/chat/ChatListener.kt
  src/main/kotlin/com/rose/gateway/minecraft/chat/LaunchIfChatExtensionEnabled.kt
  src/main/kotlin/com/rose/gateway/minecraft/chat/processing/tokens/result/MentionResult.kt
  src/main/kotlin/com/rose/gateway/minecraft/commands/arguments/ConfigArgs.kt
  src/main/kotlin/com/rose/gateway/minecraft/component/Color.kt
  src/main/kotlin/com/rose/gateway/shared/collections/Group.kt
  src/main/kotlin/com/rose/gateway/shared/text/Plurality.kt
  src/main/resources/default_gateway_config.yaml
Labels: enhancement

#51 Fixed issues with Minecraft chat parsing
  src/main/kotlin/com/rose/gateway/minecraft/chat/processing/ConvertToDiscordMessage.kt
  src/main/kotlin/com/rose/gateway/minecraft/chat/processing/tokens/RoleQuoteMentionTokenProcessor.kt
  src/main/kotlin/com/rose/gateway/minecraft/chat/processing/tokens/UserQuoteMentionTokenProcessor.kt
Labels: bug

#54 Updated README
  README.md
Labels: documentation

#56 minecraft now shows role colors of discord chatter
  src/main/kotlin/com/rose/gateway/config/schema/ChatConfig.kt
  src/main/kotlin/com/rose/gateway/discord/bot/extensions/chat/processing/DiscordMessageProcessor.kt
  src/main/resources/default_gateway_config.yaml
Labels: enhancement
